name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Log in to Azure Container Registry
      if: secrets.AZURE_REGISTRY_USERNAME && secrets.AZURE_REGISTRY_PASSWORD
      run: echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.AZURE_REGISTRY_USERNAME }}" --password-stdin ${{ secrets.AZURE_REGISTRY_URL }}

    - name: Build Docker image
      run: |
        docker build -t azureaichatapp .

    - name: Push to Docker Hub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: |
        docker tag azureaichatapp ${{ secrets.DOCKER_USERNAME }}/azureaichatapp
        docker push ${{ secrets.DOCKER_USERNAME }}/azureaichatapp

    - name: Push to Azure Container Registry
      if: secrets.AZURE_REGISTRY_USERNAME && secrets.AZURE_REGISTRY_PASSWORD
      run: |
        docker tag azureaichatapp ${{ secrets.AZURE_REGISTRY_URL }}/azureaichatapp
        docker push ${{ secrets.AZURE_REGISTRY_URL }}/azureaichatapp