name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_PASSWORD" ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        fi

    - name: Log in to Azure Container Registry
      env:
        AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
      run: |
        if [ -n "$AZURE_REGISTRY_USERNAME" ] && [ -n "$AZURE_REGISTRY_PASSWORD" ] && [ -n "$AZURE_REGISTRY_URL" ]; then
          echo "$AZURE_REGISTRY_PASSWORD" | docker login -u "$AZURE_REGISTRY_USERNAME" --password-stdin "$AZURE_REGISTRY_URL"
        fi

    - name: Build Docker image
      run: |
        docker build -t azureaichatapp .

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        if [ -n "$DOCKER_USERNAME" ]; then
          docker tag azureaichatapp "$DOCKER_USERNAME"/azureaichatapp
          docker push "$DOCKER_USERNAME"/azureaichatapp
        fi

    - name: Push to Azure Container Registry
      env:
        AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
      run: |
        if [ -n "$AZURE_REGISTRY_URL" ]; then
          docker tag azureaichatapp "$AZURE_REGISTRY_URL"/azureaichatapp
          docker push "$AZURE_REGISTRY_URL"/azureaichatapp
        fi